version: "3"
services:
  database:
    container_name: ecommerce
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=corporate_social_media
